"""Add county column to listing and merged properties

Revision ID: 21ab7fc3700d
Revises: 50402894221d
Create Date: 2024-09-06 10:30:00.729219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ab7fc3700d'
down_revision: Union[str, None] = '50402894221d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing_properties', sa.Column('county', sa.String(), nullable=True))
    op.add_column('merged_properties', sa.Column('county', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merged_properties', 'county')
    op.drop_column('listing_properties', 'county')
    # ### end Alembic commands ###
