"""Add county-specific columns to processed_properties

Revision ID: 513674e94177
Revises: 919212ba0d02
Create Date: 2024-09-06 12:37:57.439653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '513674e94177'
down_revision: Union[str, None] = '919212ba0d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_properties', sa.Column('county_buckinghamshire', sa.Boolean(), nullable=True))
    op.add_column('processed_properties', sa.Column('county_bedfordshire', sa.Boolean(), nullable=True))
    op.add_column('processed_properties', sa.Column('county_hertfordshire', sa.Boolean(), nullable=True))
    op.add_column('processed_properties', sa.Column('county_oxfordshire', sa.Boolean(), nullable=True))
    op.add_column('processed_properties', sa.Column('county_berkshire', sa.Boolean(), nullable=True))
    op.add_column('processed_properties', sa.Column('county_northamptonshire', sa.Boolean(), nullable=True))
    op.drop_column('processed_properties', 'county')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_properties', sa.Column('county', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('processed_properties', 'county_northamptonshire')
    op.drop_column('processed_properties', 'county_berkshire')
    op.drop_column('processed_properties', 'county_oxfordshire')
    op.drop_column('processed_properties', 'county_hertfordshire')
    op.drop_column('processed_properties', 'county_bedfordshire')
    op.drop_column('processed_properties', 'county_buckinghamshire')
    # ### end Alembic commands ###
