"""Classify property_type on processed_properties table

Revision ID: 5410acfc92fc
Revises: 83447f0b3ca8
Create Date: 2024-08-27 08:32:37.622053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5410acfc92fc'
down_revision: Union[str, None] = '83447f0b3ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_properties', sa.Column('property_type_Detached', sa.Boolean(), nullable=True))
    op.add_column('processed_properties', sa.Column('property_type_Semi_Detached', sa.Boolean(), nullable=True))
    op.add_column('processed_properties', sa.Column('property_type_Terraced', sa.Boolean(), nullable=True))
    op.add_column('processed_properties', sa.Column('property_type_Flat_Maisonette', sa.Boolean(), nullable=True))
    op.add_column('processed_properties', sa.Column('property_type_Other', sa.Boolean(), nullable=True))
    op.alter_column('processed_properties', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('processed_properties', 'original_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'processed_properties', 'merged_properties', ['original_id'], ['id'])
    op.drop_column('processed_properties', 'additional_features')
    op.drop_column('processed_properties', 'property_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_properties', sa.Column('property_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('processed_properties', sa.Column('additional_features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'processed_properties', type_='foreignkey')
    op.alter_column('processed_properties', 'original_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('processed_properties', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('processed_properties', 'property_type_Other')
    op.drop_column('processed_properties', 'property_type_Flat_Maisonette')
    op.drop_column('processed_properties', 'property_type_Terraced')
    op.drop_column('processed_properties', 'property_type_Semi_Detached')
    op.drop_column('processed_properties', 'property_type_Detached')
    # ### end Alembic commands ###
