"""Add synthetic_users table

Revision ID: 83447f0b3ca8
Revises: bca8cac3620f
Create Date: 2024-08-26 14:14:55.305944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83447f0b3ca8'
down_revision: Union[str, None] = 'bca8cac3620f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synthetic_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('income', sa.Float(), nullable=False),
    sa.Column('savings', sa.Float(), nullable=False),
    sa.Column('preferred_location', sa.String(), nullable=False),
    sa.Column('desired_property_type', sa.String(), nullable=False),
    sa.Column('must_have_features', sa.String(), nullable=False),
    sa.Column('nice_to_have_features', sa.String(), nullable=False),
    sa.Column('max_commute_time', sa.Integer(), nullable=False),
    sa.Column('family_size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synthetic_users_id'), 'synthetic_users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_synthetic_users_id'), table_name='synthetic_users')
    op.drop_table('synthetic_users')
    # ### end Alembic commands ###
