"""Add county and related columns to processed_properties

Revision ID: 919212ba0d02
Revises: 21ab7fc3700d
Create Date: 2024-09-06 12:20:09.852376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '919212ba0d02'
down_revision: Union[str, None] = '21ab7fc3700d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_properties', sa.Column('county', sa.String(), nullable=True))
    op.add_column('processed_properties', sa.Column('price_relative_to_county_avg', sa.Float(), nullable=True))
    op.drop_constraint('processed_properties_original_id_fkey', 'processed_properties', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('processed_properties_original_id_fkey', 'processed_properties', 'merged_properties', ['original_id'], ['id'])
    op.drop_column('processed_properties', 'price_relative_to_county_avg')
    op.drop_column('processed_properties', 'county')
    # ### end Alembic commands ###
