"""Add ProcessedProperty table

Revision ID: bca8cac3620f
Revises: 4c416d03d15c
Create Date: 2024-08-26 08:08:30.258250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca8cac3620f'
down_revision: Union[str, None] = '4c416d03d15c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_properties',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('original_id', sa.BigInteger(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('size_sq_ft', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('price_to_income_ratio', sa.Float(), nullable=True),
    sa.Column('price_to_savings_ratio', sa.Float(), nullable=True),
    sa.Column('affordability_score', sa.Float(), nullable=True),
    sa.Column('has_garden', sa.Boolean(), nullable=True),
    sa.Column('has_parking', sa.Boolean(), nullable=True),
    sa.Column('location_Urban', sa.Boolean(), nullable=True),
    sa.Column('location_Suburban', sa.Boolean(), nullable=True),
    sa.Column('location_Rural', sa.Boolean(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('epc_rating_encoded', sa.Float(), nullable=True),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.Column('additional_features', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_properties_id'), 'processed_properties', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_properties_id'), table_name='processed_properties')
    op.drop_table('processed_properties')
    # ### end Alembic commands ###
